# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 22:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date(2017, 5, 31), verbose_name='date')),
                ('nacionalidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=16)),
                ('edad', models.IntegerField()),
                ('piel', models.CharField(choices=[('B', 'Blanco'), ('N', 'Negro'), ('A', 'Asiatico')], max_length=16)),
                ('diagnosticado', models.CharField(choices=[('S', 'SI'), ('N', 'NO')], max_length=16)),
                ('biografia', models.TextField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
