# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 22:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Paciente', '0003_auto_20170531_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='imagen',
            field=models.ImageField(default=1, upload_to='images/'),
            preserve_default=False,
        ),
    ]
