# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 01:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0002_auto_20170531_2002'),
        ('Paciente', '0004_images_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='expediente',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Doctor.Doctor_info'),
            preserve_default=False,
        ),
    ]
