# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-31 22:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor_info',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('apellidos', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Mujer'), ('H', 'Hombre')], max_length=16)),
                ('edad', models.IntegerField()),
                ('cédula_profesional', models.CharField(max_length=50)),
                ('especialidad', models.CharField(choices=[('OM', 'Oncología Médica'), ('OR', 'Oncología Radioterápica'), ('D', 'Dermatología'), ('N', 'Nutrición'), ('P', 'Psicología')], max_length=16)),
                ('experiencia', models.TextField()),
                ('médico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
