# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-01 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor_info',
            name='médico',
        ),
        migrations.AddField(
            model_name='doctor_info',
            name='nombre',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
